apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: projectj-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: projectj-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

